name: The Bot Host
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 */2 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check repository
        run: |
          if [[ "${{ github.repository }}" != "ang-0u/h4x" ]]; then
            echo "This workflow can only run on the ang-0u/h4x repository."
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch latest changes
        run: git pull origin ${{ github.head_ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          sudo apt-get install jq -y
          rm -rf package-lock.json
          npm install
          npx puppeteer browsers install chrome

      - name: Set TERM environment variable
        run: export TERM=xterm

      - name: Start The Code
        run: node index.js &

      - name: keep alive
        id: check_runs
        run: |
          echo "has_new_run=false" >> $GITHUB_ENV
          for i in {1..30}; do
            sleep 10
            latest_run=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs?per_page=1&status=queued&status=in_progress" | \
              jq -r '.workflow_runs[0].id')
            if [[ $latest_run != ${{ github.run_id }} ]]; then
              echo "has_new_run=true" >> $GITHUB_ENV
              break
            fi
          done

      - name: Delete the cache and Commit the logs
        run: |
          rm -rf tmp
          mkdir tmp
          rm -rf node_modules
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'action@github.com'
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "out session update" --allow-empty)
          
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master

      - name: Stop workflow
        if: env.has_new_run == 'true'
        run: exit 0

      - name: Keep alive sleep
        if: env.has_new_run == 'false'
        run: sleep 60
